spring:
    datasource:
        url: jdbc:mysql://localhost:3306
        username: selfblog
        password: linshaojia

server:
    port: 8081
    servlet:
        context-path: /selfblog

mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.lsj.selfblog.selfblog.dao
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl