DROP SCHEMA selfblog;
CREATE SCHEMA selfblog charset UTF8MB4;
USE selfblog;


DROP TABLE IF EXISTS SELFBLOG_USER;
create TABLE SELFBLOG_USER(
  user_id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(128) NOT NULL UNIQUE ,
  password VARCHAR(128) NOT NULL) ENGINE = InnoDB DEFAULT CHARSET =UTF8MB4;
ALTER TABLE SELFBLOG_USER AUTO_INCREMENT=1000001;
INSERT INTO selfblog.selfblog_user(username,password) VALUES("admin","123456");


DROP TABLE IF EXISTS SELFBLOG_ROLE;
CREATE TABLE SELFBLOG_ROLE(
  role_id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  role_name varchar(64)
)  ENGINE = InnoDB DEFAULT CHARSET =UTF8MB4;
ALTER TABLE SELFBLOG_ROLE AUTO_INCREMENT=1000001;

INSERT SELFBLOG_ROLE(role_name) VALUE ('ADMIN');


DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE (
  user_id INT UNSIGNED NOT NULL,
  role_id INT UNSIGNED NULL,
  FOREIGN KEY(user_id) REFERENCES SELFBLOG_USER(user_id),
  FOREIGN KEY(role_id) REFERENCES SELFBLOG_ROLE(role_id)
) ENGINE = InnoDB DEFAULT CHARSET =UTF8MB4;
INSERT USER_ROLE(user_id,role_id) 
  SELECT user_id,role_id from selfblog_user,selfblog_role WHERE username = 'admin' and role_name = 'ADMIN';

  